### ISSUE TITLE
Benchmark does not return all parts

### ISSUE THREAD

**Issue by Galzzly** [yyewolf/goaoc#7]
While running the benchmark tool on my Macbook I observed that only the benchmark for Part 2 was being output, e.g.

```
goaoc b
🎄 Benching day 1 (2023):
benchmark   iter       time/iter
---------   ----       ---------
Part 2      1394    862.93 μs/op
```

Running the benchmark test manually (`go test -bench .`) I am able to see the output fro both Part 1 and Part 2 are in the output, e.g.

```
go test -bench .
goos: darwin
goarch: arm64
pkg: aocli/2023/day01
BenchmarkPartOne-10    	    1837	    590430 ns/op
BenchmarkPartTwo-10    	    1411	    862147 ns/op
PASS
ok  	aocli/2023/day01	2.645
```

From looking at the code, it would seem that the output of the benchmark on Mac is different to what would be expected, and strips away too many lines from the output slice.

```	
	// Remove the first 5 lines
	lines = lines[4:]

	// Remove the last 2 lines
	lines = lines[:len(lines)-3]
```

I would propose, instead to do something like the following, where you would identify the index of the first instance of `BenchmarkPart`, and iterate through that and the next line:

```
	i := slices.IndexFunc(lines, func(s string) bool {
		return strings.HasPrefix(s, "BenchmarkPart")
	})
	lines = lines[i:i+2]

```

**Comment by yyewolf** [comment]
Your benchmark is indeed missing the CPU line that I have on my machine, however your solution doesn't account for the random people that might rename the benchmarks.

The following solution should work and I'll push it as soon as I can :


```go
	// Find the first line with \t to locate the first benchmark line
	var firstBenchmarkLine int
	for i, line := range lines {
		if strings.Contains(line, "\t") {
			firstBenchmarkLine = i
			break
		}
	}

	// Remove the first lines
	lines = lines[firstBenchmarkLine:]
```

**Comment by Galzzly** [comment]
Have created #8 with the update

**Comment by Galzzly** [comment]
> Your benchmark is indeed missing the CPU line that I have on my machine, however your solution doesn't account for the random people that might rename the benchmarks.
> 
> The following solution should work and I'll push it as soon as I can :
> 
> ```go
> 	// Find the first line with \t to locate the first benchmark line
> 	var firstBenchmarkLine int
> 	for i, line := range lines {
> 		if strings.Contains(line, "\t") {
> 			firstBenchmarkLine = i
> 			break
> 		}
> 	}
> 
> 	// Remove the first lines
> 	lines = lines[firstBenchmarkLine:]
> ```

This makes sense, I've just updated my code to use `strings.Contains(s, "\t")` rather than `strings.HasPrefix...` and tested that the output is sane. I'll update push this up and update the PR
